name: "Holos"
description: "Platform configuration with https://holos.run"
inputs:
  version:
    description: Holos version to execute (e.g. v0.102.1)
    required: false
    default: 'v0.102.1'
  command:
    description: Holos command to execute
    required: false
    default: 'holos render platform'
  build-tags:
    description: CUE Build Tags to set as a comma separated list
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: "Pull Image"
      shell: bash
      run: docker pull --quiet ghcr.io/holos-run/holos:${{ inputs.version }}
    - name: "Flags"
      id: flags
      shell: bash
      run: |
        # flags
        FLAGS=""
        if [[ -n "${{ inputs.build-tags }}" ]]; then
          FLAGS="${FLAGS} --inject='${{inputs.build-tags}}'"
        fi
        echo "flags=${FLAGS}" >> $GITHUB_OUTPUT
    - name: "Render Manifests"
      shell: bash
      run: |
        # ${{ inputs.command }} ${{ steps.flags.outputs.flags}}
        docker run -v $(pwd):/app --workdir /app --rm ghcr.io/holos-run/holos:${{ inputs.version }} ${{inputs.command }} ${{ steps.flags.outputs.flags}}
