name: "Run Holos"
description: "Manage configuration with Holos"
inputs:
  version:
    description: Holos version to execute (e.g. v0.102.1)
    required: false
    default: 'v0.102.1'
  command:
    description: Holos command to execute
    required: false
    default: 'holos render platform'
runs:
  using: "composite"
  steps:
    - name: "Setup Holos"
      shell: bash
      run: docker pull --quiet ghcr.io/holos-run/holos:${{ inputs.version }}
    - name: "Run Holos"
      shell: bash
      run: |
        # ${{ inputs.command }}
        docker run -v $(pwd):/app --workdir /app --rm ghcr.io/holos-run/holos:${{ inputs.version }} ${{inputs.command }}
