name: "Run Holos"
description: "Manage configuration with Holos"
inputs:
  version:
    description: Holos version to execute (e.g. v0.102.1)
    required: false
    default: 'v0.102.1'
  command:
    description: Holos command to execute
    required: false
    default: 'holos render platform'
  env:
    description: environment variables as a JSON string encoded object. (e.g. '{"KEY":"value"}')
    required: false
    default: '{}'
runs:
  using: "composite"
  steps:
    - name: "Setup Holos"
      shell: bash
      run: docker pull --quiet ghcr.io/holos-run/holos:${{ inputs.version }}
    - name: "Run Holos"
      shell: bash
      env: ${{ fromJSON(inputs.env) }}
      run: |
        # ${{ inputs.command }}
        ENV_ARGS="$(jq -r 'keys | map("-e " + .) | join(" ")' <<<'${{ inputs.env }}')"
        docker run -v $(pwd):/app --workdir /app $ENV_ARGS --rm ghcr.io/holos-run/holos:${{ inputs.version }} ${{inputs.command }}
